ENGINE('B1',base64_decode(MINOC('LOC')));
ENGINE('B2',base64_decode(MINOC('RTP')));
ENGINE('B3',base64_decode(MINOC('AXC')));
ENGINE('B4',base64_decode(MINOC('RIT')));
ENGINE('B5',base64_decode(MINOC('EST')));
ENGINE('B6',base64_decode(MINOC('ESM')));
ENGINE('B7',base64_decode(MINOC('NNC')));
ENGINE('B8',base64_decode(MINOC('PTM')));
ENGINE('B9',base64_decode(MINOC('PTV')));